# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']
baseurl: "/Website/"
url: "http:://jeongjw.github.io"

sass:
  sass_dir: assets/css
  style: :nested
