#-------------------------------
# General Site Settings

title: Joshua W Jeong
description: Programmer // Photographer // Videographer // Musician
email: jeongjw@umich.edu

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Hey guys! My name is Josh Jeong and I am currently a computer science student at the University of Michigan.** 
  I hope that this website gives you a better insight on who I am and what I love to do.


#Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  #but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  #and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen. 


#-------------------------------
# Work Section

projects:
- {name: Programming, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Photo/Video, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Extracurricular, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Music, folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
#- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'facebook', link: 'https://www.facebook.com/joshjeong98'}
- {icon: 'instagram', link: 'https://www.instagram.com/_jwje/'}
#- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
#- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/joshua-jeong-422b01156'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'#
